example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),

]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import wishlist_ajax
from wishlist.views import add_wishlist
app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('ajax/', wishlist_ajax, name='wishlist_ajax'),
    path('ajax/submit/', add_wishlist, name='add_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout')
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from wishlist.models import BarangWishlist


# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Nadhira Shahnaz Zain',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

# Create your views here.
@login_required(login_url='/wishlist/login/')  
def wishlist_ajax(request):
    context = {
    'nama': 'Nadhira Shahnaz Zain',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist_ajax.html",context)

@login_required(login_url='/wishlist/login/')
@csrf_exempt
def add_wishlist(request):
    if (request.method == "POST"):
        nama = request.POST.get("nama")
        harga = request.POST.get("harga")
        deskripsi = request.POST.get("deskripsi")
        BarangWishlist.objects.create(nama_barang=nama, harga_barang=harga, deskripsi=deskripsi)
        return HttpResponse()
    else:
        print("here")
        return redirect("wishlist:show_wishlist")


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}



<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <ul class="nav nav-pills">

        <li class=""nav-item>
            <a class="nav-link" aria-current="page" href="#">{{nama}}</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="/wishlist/xml">XML</a>
        </li>
        <li class=""nav-item>
            <a class="nav-link" aria-current="page" href="#"> </a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="/wishlist/json">JSON</a>
        </li>

        </li>
        <li class=""nav-item>
            <a class="nav-link" aria-current="page" href="#"> </a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="{% url 'wishlist:logout' %}">Logout</a>
        </li>

    </div>
  </nav>
<br>
<br> 
<h1 style="text-align: center;color:#d7005d;background-color: pink;">My Main Page</h1>
<br>
<br> 
<h5>Nama: </h5>
<b>{{nama}}</b>
<br>
<br>
<div class="mx-auto" style="width: 750px;">
    <table border="2" cellpadding="8">
        <tr bgcolor="#FFC0CB">
        <th style="text-align: center;color:#d7005d">Nama Barang</th>
        <th style="text-align: center;color:#d7005d">Harga Barang</th>
        <th style="text-align: center;color:#d7005d">Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% for barang in list_barang %}
            <tr>
                <th style="text-align: center;color:hotpink">{{barang.nama_barang}}</th>
                <th style="text-align: center;color:hotpink">{{barang.harga_barang}}</th>
                <th style="text-align: center;color:hotpink">{{barang.deskripsi}}</th>
            </tr>
        {% endfor %}
    </table>
</div>
<br>
<br>
<br>
<h7>Sesi terakhir login: {{ last_login }}</h7>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block meta %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

    //POST KE AJAX SUBMIT
  $(document).ready(function(){
    
    $.get("http://localhost:8000/wishlist/json/", function(data) {
      // mengisi tabel
      for(var i = 0; i < data.length; i++){
        var tr = document.createElement("tr");

        var varNama = document.createElement("td");
        varNama.append(data[i].fields.nama_barang);

        var varHarga = document.createElement("td");
        varHarga.append(data[i].fields.harga_barang);

        var varDesk = document.createElement("td");
        varDesk.append(data[i].fields.deskripsi);
        tr.append(varNama);
        tr.append(varHarga);
        tr.append(varDesk);
        
        $(".table").append(tr);
      }
    });
    
    $("#add_wishlist").click(function(){
      var nama = $("#input_nama").val();
      var harga = $("#input_harga").val();
      var deskripsi = $("#input_deskripsi").val();

      
      $.post("http://localhost:8000/wishlist/ajax/submit/",
      {
        nama,
        harga,
        deskripsi,
      },
      function(data, status){
        console.log("add wishlist success");
        var tr = document.createElement("tr");

        var varNama = document.createElement("td");
        varNama.append(data[i].fields.nama_barang);

        var varHarga = document.createElement("td");
        varHarga.append(data[i].fields.harga_barang);

        var varDesk = document.createElement("td");
        varDesk.append(data[i].fields.deskripsi);
        tr.append(varNama);
        tr.append(varHarga);
        tr.append(varDesk);

        $(".table").append(tr);
        $("#input_nama").val("");
        $("#input_harga").val("");
        $("#input_deskripsi").val("");
      });
    });
  });
</script>
{% endblock meta %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <ul class="nav nav-pills">

        <li class=""nav-item>
            <a class="nav-link" aria-current="page" href="#">{{nama}}</a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="/wishlist/xml">XML</a>
        </li>
        <li class=""nav-item>
            <a class="nav-link" aria-current="page" href="#"> </a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="/wishlist/json">JSON</a>
        </li>

        </li>
        <li class=""nav-item>
            <a class="nav-link" aria-current="page" href="#"> </a>
        </li>

        <li class="nav-item">
            <a class="nav-link active" href="{% url 'wishlist:logout' %}">Logout</a>
        </li>

    </div>
  </nav>
<br>
<br> 
<h1 style="text-align: center;color:#d7005d;background-color: pink;">My Main Page</h1>
<br>
<br> 
<h5>Nama: </h5>
<b>{{nama}}</b>
<br>
<br>

<div class="table" style="width: 750px;">
    <table border="2" cellpadding="8">
        <tr bgcolor="#FFC0CB">
        <th style="text-align: center;color:#d7005d">Nama Barang</th>
        <th style="text-align: center;color:#d7005d">Harga Barang</th>
        <th style="text-align: center;color:#d7005d">Deskripsi</th>
        </tr>

    </table>
</div>
<br>
<br>
<br>
<h7>Sesi terakhir login: {{ last_login }}</h7>


<div>
    <h1>Create New Wishlist</h1>
    <form method="POST" action="{% url 'wishlist:add_wishlist' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>Nama Barang</td>
                <td><input type="text" name="nama_barang" placeholder="nama barang" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Harga Barang</td>
                <td><input type="text" name="harga_barang" placeholder="harga barang" class="form-control"></td>
            </tr>
            <tr>
                <td>Deskripsi</td>
                <td><input type="text" name="deskripsi" placeholder="deskripsi" class="form-control"></td>
            </tr>
        </table>
        
        <center><input class="button" type="submit" value="Add Wishlist"></center>
    </form>
</div>



{% endblock content %}